name: CI/CD 

on:
  push:
    branches:
      - main
      
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install psycopg2-binary
          pip install pytest

      - name: Prepare for tests (compose up)
        run: docker compose up -d --build
  
      - name: Wait services to start
        run: sleep 10
  
      - name: Run integration test
        run: python tests/integration.py


      - name: Run component test
        run: python tests/component.py
        

      - name: Clean up (compose down)
        run: docker compose down

  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker buildx create --use
          docker buildx inspect
          docker buildx build --platform linux/amd64,linux/arm64 -t dontplayw1thme/delivery-service:latest -t dontplayw1thme/delivery-service:${{ github.sha }} --push -f delivery_service/Dockerfile .

